sonar.projectKey=virtualbuddy-angular
sonar.projectName=virtualbuddy-angular
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/polyfills.ts

sonar.javascript.lcov.reportPaths=coverage/**/lcov.info